package sh.harold.fulcrum.control.lifecycle;

public enum ExperienceSessionRejectionReason {
    PRINCIPAL_MISMATCH,
    STALE_FENCING_EPOCH,
    DEADLINE_EXPIRED,
    REVISION_MISMATCH,
    IDEMPOTENCY_CONFLICT,
    AGGREGATE_MISMATCH,
    CONTRACT_MISMATCH,
    SESSION_ALREADY_EXISTS,
    SESSION_NOT_REQUESTED,
    SESSION_NOT_PLACED,
    SESSION_NOT_ACTIVE,
    SESSION_TERMINAL,
    UNKNOWN_COMMAND
}
