package sh.harold.fulcrum.control.queue;

public enum QueueRosterRejectionReason {
    PRINCIPAL_MISMATCH,
    STALE_FENCING_EPOCH,
    DEADLINE_EXPIRED,
    REVISION_MISMATCH,
    IDEMPOTENCY_CONFLICT,
    AGGREGATE_MISMATCH,
    CONTRACT_MISMATCH,
    QUEUE_INTENT_ALREADY_EXISTS,
    QUEUE_INTENT_NOT_WAITING,
    DUPLICATE_SUBJECT_IN_WAITING_QUEUE,
    ROSTER_INTENT_ALREADY_EXISTS,
    EMPTY_ROSTER,
    INCOMPATIBLE_QUEUE_INTENTS,
    QUEUE_INTENT_EXPIRED,
    ROSTER_CAPACITY_EXCEEDED,
    DUPLICATE_SUBJECT_IN_ROSTER,
    UNKNOWN_COMMAND
}
