manifest.version=2
node-kind=PAPER
forbid-local-authority=true
forbid-direct-store-config=true
forbidden-capabilities=authority.local,authority.command.message-bus,store.direct.sql,store.direct.document,store.migration.resources,driver.jdbc.sql,pool.direct.sql
data-authority.command-schema-version=1
data-authority.command-contract-fingerprint=71b55c2b17c1b024016955b653faae965d7dca30ac31d0d5d64e3afd26226ef8
data-authority.read-schema-version=1
data-authority.read-contract-fingerprint=9cdbdc46288e8f2cdb82e83f9953cb664a649181c0c5eeebeaaad738e2260089
