manifest.version=2
node-kind=PAPER
forbid-local-authority=true
forbid-direct-store-config=true
forbidden-capabilities=authority.local,authority.command.message-bus,store.direct.sql,store.direct.document,store.migration.resources,driver.jdbc.sql,pool.direct.sql
data-authority.command-schema-version=1
data-authority.command-contract-fingerprint=1cb22b657dad54a157d23ca60534046c895945753756c37f7c645e6e4e1af7e7
data-authority.read-schema-version=1
data-authority.read-contract-fingerprint=9cdbdc46288e8f2cdb82e83f9953cb664a649181c0c5eeebeaaad738e2260089
