# Dirty Data Cache Configuration
# This file configures the dirty data tracking system for player data persistence

cache:
  # Cache type: 'memory' or 'redis'
  # - memory: Fast, in-memory cache (not persistent across server restarts)
  # - redis: Persistent, distributed cache (requires Redis server)
  type: memory
  
  # Whether to fallback to memory cache if Redis is unavailable
  # Only applies when cache type is 'redis'
  fallback-to-memory: true
  
  # Time-to-live for cache entries (format: 1h, 30m, 60s, 500ms)
  # Entries older than this will be automatically cleaned up
  entry-ttl: 1h
  
  # Health check interval for Redis connections (format: 1h, 30m, 60s, 500ms)
  # Set to 0 to disable health checks
  health-check-interval: 5m
  
  # Redis-specific configuration
  redis:
    # Redis server connection settings
    host: localhost
    port: 6379
    database: 0
    password: # Leave empty for no password
    
    # Connection timeout and retry settings
    connection-timeout: 5s
    retry-delay: 500ms
    max-retries: 3
    
    # Connection pool settings
    pool:
      max-connections: 20
      max-idle-connections: 10
      min-idle-connections: 5

# Example configurations for different environments:

# Development/Testing (in-memory)
# cache:
#   type: memory
#   entry-ttl: 30m

# Production (Redis with authentication)
# cache:
#   type: redis
#   fallback-to-memory: true
#   entry-ttl: 2h
#   health-check-interval: 2m
#   redis:
#     host: redis.example.com
#     port: 6379
#     database: 1
#     password: your-redis-password
#     connection-timeout: 10s
#     retry-delay: 1s
#     max-retries: 5
#     pool:
#       max-connections: 50
#       max-idle-connections: 25
#       min-idle-connections: 10

# High-performance setup (Redis with optimized pool)
# cache:
#   type: redis
#   fallback-to-memory: false
#   entry-ttl: 6h
#   health-check-interval: 30s
#   redis:
#     host: redis-cluster.example.com
#     port: 6379
#     database: 0
#     connection-timeout: 2s
#     retry-delay: 100ms
#     max-retries: 10
#     pool:
#       max-connections: 100
#       max-idle-connections: 50
#       min-idle-connections: 20