config-version = "2.8"
bind = "0.0.0.0:25565"
motd = "Fulcrum Lobby"
show-max-players = 100
online-mode = false
force-key-authentication = false
prevent-client-proxy-connections = false
player-info-forwarding-mode = "none"
enable-player-address-logging = true

[advanced]
login-ratelimit = 0

[servers]
lobby = "127.0.0.1:25566"
try = []

[forced-hosts]
