package sh.harold.fulcrum.data.codegen;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import sh.harold.fulcrum.api.contract.CommandName;
import sh.harold.fulcrum.api.contract.ContractName;
import sh.harold.fulcrum.api.contract.EventName;
import sh.harold.fulcrum.data.contract.CommandDeclaration;
import sh.harold.fulcrum.data.contract.ContractDeclaration;
import sh.harold.fulcrum.data.contract.EventDeclaration;
import sh.harold.fulcrum.data.contract.FieldDeclaration;
import sh.harold.fulcrum.data.contract.FieldType;
import sh.harold.fulcrum.data.contract.ProjectionDeclaration;
import sh.harold.fulcrum.data.contract.SnapshotDeclaration;
import sh.harold.fulcrum.data.contract.TopicDeclaration;
import sh.harold.fulcrum.data.contract.TopicFamily;

import javax.tools.ToolProvider;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class ContractCodeGeneratorTest {
    private final ContractCodeGenerator generator = new ContractCodeGenerator();

    @Test
    void generatesHelloWorldContractPacketArtifacts() {
        GeneratedContractPacket packet = generator.generate(helloWorldContract());

        assertEquals(List.of(
                "contracts/hello-world/contract-ledger.json",
                "manifests/hello-world.topics.json",
                "migrations/hello-world.sql",
                "src/main/java/sh/harold/fulcrum/generated/contracts/GreetingAccepted.java",
                "src/main/java/sh/harold/fulcrum/generated/contracts/HelloWorldAuthorityStub.java",
                "src/main/java/sh/harold/fulcrum/generated/contracts/HelloWorldCommandClient.java",
                "src/main/java/sh/harold/fulcrum/generated/contracts/HelloWorldSerializer.java",
                "src/main/java/sh/harold/fulcrum/generated/contracts/SayHello.java"
        ), packet.artifacts().stream().map(GeneratedArtifact::path).toList());

        assertEquals("""
                -- Generated by contract-codegen-v1 for contract hello-world.
                -- Inert migration artifact; services must not execute schema creation at startup.
                CREATE TABLE hello_world_greeting_projection (
                    aggregate_id TEXT NOT NULL,
                    greeting TEXT NOT NULL,
                    accepted_at TIMESTAMPTZ NOT NULL,
                    revision BIGINT NOT NULL
                );
                """, packet.artifact("migrations/hello-world.sql").contents());

        String topicManifest = packet.artifact("manifests/hello-world.topics.json").contents();
        assertTrue(topicManifest.contains("\"contract\": \"hello-world\""));
        assertTrue(topicManifest.contains("\"name\": \"cmd.hello-world\""));
        assertTrue(topicManifest.contains("\"family\": \"COMMAND\""));
        assertTrue(topicManifest.contains("\"name\": \"evt.hello-world\""));
        assertTrue(topicManifest.contains("\"family\": \"EVENT\""));

        String ledger = packet.artifact("contracts/hello-world/contract-ledger.json").contents();
        assertTrue(ledger.contains("\"generator\": \"contract-codegen-v1\""));
        assertTrue(ledger.contains("\"fingerprint\": \"" + packet.declarationFingerprint() + "\""));
        assertEquals(64, packet.declarationFingerprint().length());
    }

    @Test
    void generatedHelloWorldSourcesCompileAndSerializerRoundTrips(@TempDir Path tempDir) throws Exception {
        GeneratedContractPacket packet = generator.generate(helloWorldContract());
        Path classesDir = compileGeneratedSources(packet, tempDir);

        try (URLClassLoader loader = new URLClassLoader(new java.net.URL[]{classesDir.toUri().toURL()}, getClass().getClassLoader())) {
            Class<?> payloadClass = loader.loadClass("sh.harold.fulcrum.generated.contracts.SayHello");
            Constructor<?> payloadConstructor = payloadClass.getConstructor(String.class, Instant.class);
            Object payload = payloadConstructor.newInstance("hi=there\nfriend", Instant.parse("2026-06-16T07:00:00Z"));

            Class<?> serializerClass = loader.loadClass("sh.harold.fulcrum.generated.contracts.HelloWorldSerializer");
            Object serializer = serializerClass.getConstructor().newInstance();
            Method encode = serializerClass.getMethod("encodeSayHello", payloadClass);
            Method decode = serializerClass.getMethod("decodeSayHello", String.class);

            String encoded = (String) encode.invoke(serializer, payload);
            Object decoded = decode.invoke(serializer, encoded);

            assertEquals(payload, decoded);
        }
    }

    @Test
    void refusesContractWithoutProjectionForMigrationOutput() {
        ContractDeclaration declaration = new ContractDeclaration(
                new ContractName("hello-world"),
                List.of(new CommandDeclaration(new CommandName("say-hello"), "SayHello", List.of(new FieldDeclaration("greeting", FieldType.STRING)), false)),
                List.of(new EventDeclaration(new EventName("greeting-accepted"), "GreetingAccepted", List.of(new FieldDeclaration("greeting", FieldType.STRING)))),
                Optional.of(new SnapshotDeclaration("HelloWorldSnapshot", List.of(new FieldDeclaration("revision", FieldType.LONG)))),
                List.of(),
                List.of(new TopicDeclaration("cmd.hello-world", TopicFamily.COMMAND)));

        IllegalArgumentException exception = org.junit.jupiter.api.Assertions.assertThrows(
                IllegalArgumentException.class,
                () -> generator.generate(declaration));

        assertEquals("contract must declare at least one projection for migration output", exception.getMessage());
    }

    private static Path compileGeneratedSources(GeneratedContractPacket packet, Path tempDir) throws IOException {
        Path sourceRoot = tempDir.resolve("sources");
        Path classesDir = tempDir.resolve("classes");
        Files.createDirectories(classesDir);
        List<Path> sources = packet.artifacts().stream()
                .filter(artifact -> artifact.path().endsWith(".java"))
                .map(artifact -> writeGeneratedSource(sourceRoot, artifact))
                .toList();

        var compiler = ToolProvider.getSystemJavaCompiler();
        assertNotNull(compiler, "JDK compiler is required for generated source validation");
        try (var fileManager = compiler.getStandardFileManager(null, Locale.ROOT, StandardCharsets.UTF_8)) {
            var compilationUnits = fileManager.getJavaFileObjectsFromPaths(sources);
            ByteArrayOutputStream errors = new ByteArrayOutputStream();
            boolean compiled = compiler.getTask(
                    new OutputStreamWriter(errors, StandardCharsets.UTF_8),
                    fileManager,
                    null,
                    List.of("-classpath", System.getProperty("java.class.path"), "-d", classesDir.toString()),
                    null,
                    compilationUnits).call();
            assertTrue(compiled, () -> errors.toString(StandardCharsets.UTF_8));
        }
        return classesDir;
    }

    private static Path writeGeneratedSource(Path sourceRoot, GeneratedArtifact artifact) {
        try {
            Path source = sourceRoot.resolve(artifact.path().replace("src/main/java/", ""));
            Files.createDirectories(source.getParent());
            Files.writeString(source, artifact.contents(), StandardCharsets.UTF_8);
            return source;
        } catch (IOException exception) {
            throw new IllegalStateException("Could not write generated source " + artifact.path(), exception);
        }
    }

    private static ContractDeclaration helloWorldContract() {
        return new ContractDeclaration(
                new ContractName("hello-world"),
                List.of(new CommandDeclaration(
                        new CommandName("say-hello"),
                        "SayHello",
                        List.of(
                                new FieldDeclaration("greeting", FieldType.STRING),
                                new FieldDeclaration("requestedAt", FieldType.INSTANT)),
                        false)),
                List.of(new EventDeclaration(
                        new EventName("greeting-accepted"),
                        "GreetingAccepted",
                        List.of(
                                new FieldDeclaration("greeting", FieldType.STRING),
                                new FieldDeclaration("acceptedAt", FieldType.INSTANT)))),
                Optional.of(new SnapshotDeclaration(
                        "HelloWorldSnapshot",
                        List.of(
                                new FieldDeclaration("greeting", FieldType.STRING),
                                new FieldDeclaration("revision", FieldType.LONG)))),
                List.of(new ProjectionDeclaration(
                        "helloWorldGreetingProjection",
                        "hello_world_greeting_projection",
                        List.of(
                                new FieldDeclaration("aggregateId", FieldType.STRING),
                                new FieldDeclaration("greeting", FieldType.STRING),
                                new FieldDeclaration("acceptedAt", FieldType.INSTANT),
                                new FieldDeclaration("revision", FieldType.LONG)))),
                List.of(
                        new TopicDeclaration("cmd.hello-world", TopicFamily.COMMAND),
                        new TopicDeclaration("evt.hello-world", TopicFamily.EVENT),
                        new TopicDeclaration("state.hello-world", TopicFamily.STATE),
                        new TopicDeclaration("rsp.hello-world", TopicFamily.RESPONSE)));
    }
}
