package sh.harold.fulcrum.control.route;

public enum RouteAttemptRejectionReason {
    PRINCIPAL_MISMATCH,
    STALE_FENCING_EPOCH,
    DEADLINE_EXPIRED,
    REVISION_MISMATCH,
    IDEMPOTENCY_CONFLICT,
    AGGREGATE_MISMATCH,
    CONTRACT_MISMATCH,
    ROUTE_ATTEMPT_ALREADY_EXISTS,
    ROUTE_ATTEMPT_NOT_OPENED,
    DEADLINE_NOT_REACHED,
    INVALID_TRANSITION,
    UNKNOWN_COMMAND
}
