package sh.harold.fulcrum.standard.realm;

public enum RealmSnapshotLineageRejectionReason {
    DUPLICATE_SNAPSHOT_ID,
    MALFORMED_DIGEST_REFERENCE,
    OBJECT_ADDRESS_MISMATCH,
    UNSUPPORTED_STATE_COMPATIBILITY,
    PARENT_SNAPSHOT_MISSING,
    PARENT_SCOPE_MISMATCH,
    PARENT_CAPTURED_NOT_EARLIER,
    PARENT_REVISION_NOT_EARLIER
}
