package sh.harold.fulcrum.control.instance;

public enum InstanceRegistryRejectionReason {
    DEADLINE_EXPIRED,
    PRINCIPAL_MISMATCH,
    STALE_FENCING_EPOCH,
    REVISION_MISMATCH,
    IDEMPOTENCY_CONFLICT,
    AGGREGATE_MISMATCH,
    CONTRACT_MISMATCH,
    INSTANCE_ALREADY_REGISTERED,
    INSTANCE_NOT_REGISTERED,
    INSTANCE_OFFLINE,
    UNKNOWN_COMMAND
}
