package sh.harold.fulcrum.core.content;

public enum ContentValidationRejectionReason {
    MALFORMED_DIGEST_REFERENCE,
    OBJECT_ADDRESS_MISMATCH,
    NON_POSITIVE_BYTE_LENGTH,
    NON_POSITIVE_ROTATION_WEIGHT,
    CONTRACT_PINS_MISSING,
    MAP_TEMPLATE_SCOPE_MISSING,
    CONFIG_MODE_SCOPE_MISSING,
    STATE_COMPATIBILITY_MISSING,
    DUPLICATE_ARTIFACT_PIN,
    DUPLICATE_SELECTION_ORDER
}
