package sh.harold.fulcrum.control.fault;

public enum FaultRejectionReason {
    PRINCIPAL_MISMATCH,
    STALE_FENCING_EPOCH,
    DEADLINE_EXPIRED,
    REVISION_MISMATCH,
    IDEMPOTENCY_CONFLICT,
    AGGREGATE_MISMATCH,
    CONTRACT_MISMATCH,
    FAULT_NOT_FOUND,
    FAULT_IDENTITY_MISMATCH,
    FAULT_ALREADY_RELEASED,
    UNKNOWN_COMMAND
}
