# Fulcrum Core Configuration
# This file contains the main configuration for Fulcrum

# Development mode enables additional debugging features
# and relaxed security checks for development environments
development-mode: true

# Module System Configuration
module:
  # Directory where modules are stored
  directory: modules

# Slot family host filters (docs/slot-family-discovery-notes.md)
# allow: optional whitelist of familyIds; when empty all families are permitted
# deny: optional blacklist of familyIds applied after the allow list
slot-family-filters:
  allow: []
  deny: []
