# Fulcrum Core Configuration
# This file contains the main configuration for Fulcrum

# Development mode enables additional debugging features
# and relaxed security checks for development environments
development-mode: true

# Module System Configuration
module:
  # Directory where modules are stored
  directory: modules