# Fulcrum Velocity Configuration

# Redis configuration (shared for all Redis-based features)
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

# Server lifecycle management
server-lifecycle:
  enabled: true
  heartbeat-interval: 30  # seconds
  registration-timeout: 60  # seconds
  
  # Simplified capacity configuration
  capacity:
    hard-cap: 1000  # Maximum players allowed (hard limit)
    soft-cap: 500   # Preferred player limit (soft limit for load balancing)

# Message Bus Configuration
message-bus:
  # Mode: "redis" for distributed or "simple" for local-only
  mode: redis

# Identity Configuration
identity:
  # Enable identity management
  enabled: true

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARN, ERROR)
  level: INFO
  # Enable debug logging for specific features
  debug:
    server-lifecycle: false
    message-bus: false
    identity: false