# Database configuration for Fulcrum Data API - Velocity
storage:
  # Backend type: JSON or MONGODB
  type: JSON
  
# JSON file storage settings (if type is JSON)
json:
  # Directory where JSON files will be stored
  data-path: "data"
  # Cache settings
  cache:
    enabled: true
    max-size: 1000
    
# MongoDB settings (if type is MONGODB)
mongodb:
  connection-string: "mongodb://localhost:27017"
  database: "fulcrum_velocity"
  # Optional authentication
  username: ""
  password: ""