# Database configuration for Fulcrum Data API - Velocity
storage:
  # Backend type: JSON or MONGODB
  type: JSON
  
# JSON file storage settings (if type is JSON)
json:
  # Directory where JSON files will be stored
  data-path: "data"
  # Cache settings
  cache:
    enabled: true
    max-size: 1000
    
# MongoDB settings (if type is MONGODB)
mongodb:
  connection-string: "mongodb://localhost:27017"
  database: "fulcrum_velocity"
  # Optional authentication
  username: ""
  password: ""

# Redis configuration for Message Bus
redis:
  # Enable/disable Redis. When disabled, uses in-memory message bus
  enabled: true
  # Redis server host
  host: localhost
  # Redis server port
  port: 6379
  # Database index to use
  database: 0
  # Redis password (optional)
  password: ""
  # Connection timeout in milliseconds
  connection-timeout: 2000
  # Connection pool configuration
  connection-pool:
    min-idle: 1
    max-idle: 8
    max-total: 8