package sh.harold.fulcrum.velocity.party;

enum PartyErrorCode {
    NONE,
    NOT_IN_PARTY,
    ALREADY_IN_PARTY,
    NOT_LEADER,
    NOT_MODERATOR,
    TARGET_NOT_FOUND,
    TARGET_ALREADY_IN_PARTY,
    TARGET_NOT_IN_PARTY,
    INVITE_NOT_FOUND,
    INVITE_ALREADY_PENDING,
    INVITE_EXPIRED,
    PARTY_FULL,
    EXCEEDS_TEAM_SIZE,
    LEADER_ONLY_ACTION,
    CANNOT_TARGET_SELF,
    REDIS_UNAVAILABLE,
    UNKNOWN
}
