# Example configuration for local development
# Copy this to run/plugins/fulcrum-velocity/config.yml after first run

# Redis configuration for message bus (using Lettuce client)
redis:
  enabled: true
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  timeout: 2000
  
  # Lettuce connection pool settings
  pool:
    maxConnections: 20
    minIdleSize: 5
    connectionTimeout: 10000
    commandTimeout: 2000
    shutdownTimeout: 2000

# Message bus settings
message-bus:
  enabled: true
  # Unique identifier for this proxy instance
  server-id: "velocity-dev"
  
  # Channel prefixes for Redis pub/sub
  channels:
    global: "fulcrum:global"
    server: "fulcrum:server:"
    player: "fulcrum:player:"
  
  # Player location tracking
  player-tracking:
    enabled: true
    # How long to cache player locations (milliseconds)
    cache-ttl: 5000
    # Redis key prefix for player locations
    key-prefix: "fulcrum:players:"
    # Update interval for player locations (milliseconds)
    update-interval: 1000

# Debug settings for development
debug:
  # Enable verbose logging
  verbose: false
  # Log Redis operations
  log-redis: false
  # Log message bus events
  log-messages: false
  # Log player join/leave events
  log-player-events: false

# Feature toggles
features:
  # Enable player identity management
  identity: true
  # Enable cross-server messaging
  messaging: true
  # Enable player location tracking
  location-tracking: true

# Performance settings
performance:
  # Maximum concurrent Redis operations
  max-concurrent-operations: 100
  # Buffer size for message queues
  message-buffer-size: 1000
  # Thread pool size for async operations
  thread-pool-size: 4